# Generated by Django 3.2.12 on 2022-09-21 23:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo do paciente', max_length=50, verbose_name='Nome')),
                ('titular', models.CharField(help_text='Digite seu nome completo do titular', max_length=50, verbose_name='Titular')),
                ('nascimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('rg', models.CharField(help_text='99.999.999-9', max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(help_text='999.999.999-90', max_length=15, verbose_name='CPF')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('telefone', models.CharField(help_text='(DD)99999-9999', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo do médico', max_length=50, verbose_name='Nome')),
                ('nascimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('rg', models.CharField(help_text='99.999.999-9', max_length=15, verbose_name='RG')),
                ('crm', models.CharField(max_length=15, verbose_name='CRM')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('telefone', models.CharField(help_text='(DD)99999-9999', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cidade')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo do funcionário', max_length=50, verbose_name='Nome')),
                ('nascimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('rg', models.CharField(help_text='99.999.999-9', max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(help_text='999.999.999-90', max_length=15, verbose_name='CPF')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('telefone', models.CharField(help_text='(DD)99999-9999', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.datetime.now)),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
