# Generated by Django 3.2.12 on 2022-09-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='status',
        ),
    ]
