# Generated by Django 3.2.12 on 2022-09-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_remove_paciente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='Ativo', max_length=20),
        ),
    ]
