# Generated by Django 3.2.12 on 2022-09-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_paciente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Digite o nome completo do funcionario', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Anativo', 'Inativo')], default='Ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(help_text='Digite o nome completo do médico', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Anativo', 'Inativo')], default='Ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(help_text='Digite o nome completo do paciente', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Anativo', 'Inativo')], default='Ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='titular',
            field=models.CharField(help_text='Digite o nome completo do titular', max_length=50, verbose_name='Titular'),
        ),
    ]
