# Generated by Django 3.2.12 on 2022-11-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_medico_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
