# Generated by Django 3.2.12 on 2022-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_auto_20220921_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(max_length=5, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
